/******************************************************************************
This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*******************************************************************************/

/*
local_hbm_bandwidth_model_test.cc -- multi-user local-HBM bandwidth
contention fixture (hbm-bandwidth-contention).

Runs the static ET simulation (entry replicated from the step-1-3
completion fixture -- test-only duplicate, never part of the baseline
gates) over the synthetic 2-rank graph generated by
tests/make_local_hbm_fixture_et.py, in two network scenarios:

  fast  link 100 GB/s: the network side of every p2p transfer finishes
        long before the endpoint HBM job (network-first join order);
  slow  link 0.5 GB/s: the endpoint HBM job finishes long before the
        network side (HBM-first join order).

Numeric model under test (local-mem-bw 6 GB/s = 6 B/ns, latency 100 ns):

  rank 0 HBM users, all issued at tick 0:
    COMP       tensor_size 30 B   (roofline traffic, read+write merged)
    COMM_READ  60 B              (send endpoint of the 60 B transfer)
    COMM_WRITE 120 B             (recv endpoint of the 120 B transfer)
  Equal split of the single 6 B/ns scalar among N users:
    [100,115)  3 users @ 6/3 = 2 B/ns each -> COMP (30 B) drains in 15 ns
               -> completes at 115 (each of the three users really received
               exactly 1/3 of the rate);
    [115,125)  2 users @ 6/2 = 3 B/ns  -> COMM_READ (30 B left) drains in
               10 ns -> completes at 125 (the two survivors each received
               exactly 1/2 after the first completion);
    [125,135)  1 user  @ 6 B/ns         -> COMM_WRITE (60 B left) drains
               in 10 ns -> completes at 135.

  rank 1 HBM users: COMM_WRITE 60 B + COMM_READ 120 B (2-user case):
    [100,120)  2 users @ 3 B/ns -> WRITE completes at 120;
    [120,130)  1 user  @ 6 B/ns -> READ completes at 130.

  Node completion = join(network callback, endpoint HBM job), fired
  exactly once per node; the ranks' 4th/3rd nodes carry hbm-charge=false
  and complete on the network event alone (they also wait for the static
  single comm slot).  Fast-network joins complete at the HBM ticks above;
  slow-network joins complete at the network ticks.  The fluid drain rate
  of a yml "GB/s" link is bandwidth * 2^30 / 1e9 B/ns (NetworkFunction
  convention, 1 GB = 2^30 B): the 0.5 link drains at 0.536870912 B/ns, so
  60 B takes ceil(111.76)=112 ns, 120 B takes ceil(223.52)=224 ns and
  40 B takes ceil(74.51)=75 ns, each +20 ns propagation latency.

Expected completions (tick == exact value, and each (rank, node) fires
exactly once):
  fast: rank0 {1:115, 2:125, 3:135, 4:146}, rank1 {1:130, 2:120, 3:146}
  slow: rank0 {1:115, 2:132, 3:244, 4:227}, rank1 {1:244, 2:132, 3:227}
  (slow rank0 node 4 issues at 132, when the joined send frees the comm
  slot: 132 + 75 + 20 = 227)

Model side-band counters (identical in both scenarios; the HBM side does
not depend on the network):
  rank0 busy 35 ns, comp 30, comm_read 60, comm_write 120 served bytes,
        peak concurrency 3, redistribution events 4
  rank1 busy 30 ns, comm_read 120, comm_write 60, peak 2, events 2

Build: cmake --build build/astra_analytical/build_congestion_aware --target
       AstraSim_Analytical_Congestion_Aware_LocalHbmTest -j
Run (from template/astra-sim-face, after generating the fixture):
  python3 astra-sim/workload/execution_driven/tests/make_local_hbm_fixture_et.py
  build/astra_analytical/build_congestion_aware/AstraSim_Analytical/\
      AstraSim_Analytical_Congestion_Aware_LocalHbmTest --scenario fast
  (same binary with --scenario slow / --scenario legacy; the system and
  network configurations default to the fixture set)
Exit code 0 on ALL PASS.
*/

#include "astra-sim/common/Logging.hh"
#include "astra-sim/system/Sys.hh"
#include "astra-sim/workload/LocalHbmBandwidthModel.hh"
#include "astra-sim/workload/MetricCollector.hh"
#include "astra-sim/workload/Workload.hh"
#include "astra-sim/workload/execution_driven/CompletionObserver.hh"
#include "common/CmdLineParser.hh"
#include "congestion_aware/CongestionAwareNetworkApi.hh"
#include <remote_memory_backend/analytical/AnalyticalRemoteMemory.hh>
#include <astra-network-analytical/common/EventQueue.h>
#include <astra-network-analytical/common/NetworkParser.h>
#include <astra-network-analytical/congestion_aware/Helper.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <string>
#include <vector>

using namespace AstraSim;
using namespace Analytical;
using namespace AstraSimAnalytical;
using namespace AstraSimAnalyticalCongestionAware;
using namespace NetworkAnalytical;
using namespace NetworkAnalyticalCongestionAware;

namespace {

struct CompletionRecord {
    uint64_t tick = 0;
    uint64_t fires = 0;
};

// rank -> node_id -> completion record
std::map<int, std::map<uint64_t, CompletionRecord>> g_completions;

void collecting_hook(void* /*ctx*/, int rank, uint64_t node_id,
                     const char* /*request_id*/, const char* /*stage*/,
                     uint64_t /*generation*/, uint64_t tick,
                     int terminal_status) {
    if (terminal_status !=
        static_cast<int>(ExecutionDriven::NodeTerminalStatus::Success)) {
        std::fprintf(stderr,
                     "[local_hbm_test] unexpected terminal_status=%d "
                     "(rank %d node %llu)\n",
                     terminal_status, rank,
                     static_cast<unsigned long long>(node_id));
        std::exit(1);
    }
    auto& record = g_completions[rank][node_id];
    record.tick = tick;
    record.fires++;
}

bool expect_tick(int rank, uint64_t node_id, uint64_t expected) {
    const auto rank_it = g_completions.find(rank);
    if (rank_it == g_completions.end() ||
        rank_it->second.find(node_id) == rank_it->second.end()) {
        std::fprintf(stderr,
                     "[local_hbm_test] FAIL: rank %d node %llu never "
                     "completed\n",
                     rank, static_cast<unsigned long long>(node_id));
        return false;
    }
    const CompletionRecord& record = rank_it->second.at(node_id);
    bool ok = true;
    if (record.tick != expected) {
        std::fprintf(stderr,
                     "[local_hbm_test] FAIL: rank %d node %llu completed at "
                     "%llu, expected %llu\n",
                     rank, static_cast<unsigned long long>(node_id),
                     static_cast<unsigned long long>(record.tick),
                     static_cast<unsigned long long>(expected));
        ok = false;
    }
    if (record.fires != 1) {
        std::fprintf(stderr,
                     "[local_hbm_test] FAIL: rank %d node %llu fired %llu "
                     "times, expected exactly once\n",
                     rank, static_cast<unsigned long long>(node_id),
                     static_cast<unsigned long long>(record.fires));
        ok = false;
    }
    return ok;
}

bool expect_double(double actual, double expected, const char* what) {
    if (std::abs(actual - expected) > 1e-6) {
        std::fprintf(stderr,
                     "[local_hbm_test] FAIL: %s = %.9f, expected %.9f\n",
                     what, actual, expected);
        return false;
    }
    return true;
}

bool expect_uint(uint64_t actual, uint64_t expected, const char* what) {
    if (actual != expected) {
        std::fprintf(stderr,
                     "[local_hbm_test] FAIL: %s = %llu, expected %llu\n",
                     what, static_cast<unsigned long long>(actual),
                     static_cast<unsigned long long>(expected));
        return false;
    }
    return true;
}

}  // namespace

int main(int argc, char* argv[]) {
    std::string scenario = "fast";
    std::string fixture_root = "sh_test_mesh/generated/local_hbm_fixture";
    for (int i = 1; i < argc; ++i) {
        if (std::strncmp(argv[i], "--scenario=", 11) == 0) {
            scenario = argv[i] + 11;
        } else if (std::strncmp(argv[i], "--fixture-root=", 15) == 0) {
            fixture_root = argv[i] + 15;
        }
    }
    if (scenario != "fast" && scenario != "slow" && scenario != "legacy") {
        std::fprintf(stderr,
                     "[local_hbm_test] --scenario must be fast|slow|legacy\n");
        return 1;
    }

    // Parse the standard command line arguments (same parser/defaults as the
    // other fixtures; logging/metrics stay off).  The two fixture-local
    // flags (--scenario / --fixture-root) are consumed above and stripped
    // from the argv handed to the shared cxxopts parser (unknown options
    // confuse its value handling).  The legacy scenario swaps in the
    // flag-off system.json over the fast network; everything else is
    // fixture-internal.
    const std::string network_dir =
        (scenario == "slow") ? "/slow/" : "/fast/";
    const std::string system_path = fixture_root +
        ((scenario == "legacy") ? "/legacy/system.json" : "/system.json");
    std::vector<char*> passthrough;
    passthrough.push_back(argv[0]);
    // Fixture-internal defaults for the three no-default shared options; the
    // shared CmdLineParser::get exit(-1)s on a never-provided option with no
    // default, so every option read below is guaranteed present.  The strings
    // must outlive passthrough, hence the named locals.
    bool has_workload = false, has_network = false;
    for (int i = 1; i < argc; ++i) {
        if (std::strncmp(argv[i], "--scenario=", 11) == 0 ||
            std::strncmp(argv[i], "--fixture-root=", 15) == 0) {
            continue;
        }
        if (std::strncmp(argv[i], "--workload-configuration", 25) == 0) {
            has_workload = true;
        }
        if (std::strncmp(argv[i], "--network-configuration", 24) == 0) {
            has_network = true;
        }
        passthrough.push_back(argv[i]);
    }
    const std::string default_workload = "--workload-configuration=" +
        fixture_root + "/fixture";
    const std::string default_network = "--network-configuration=" +
        fixture_root + network_dir + "network.yml";
    if (!has_workload) {
        passthrough.push_back(const_cast<char*>(default_workload.c_str()));
    }
    if (!has_network) {
        passthrough.push_back(const_cast<char*>(default_network.c_str()));
    }
    auto cmd_line_parser = CmdLineParser(argv[0]);
    cmd_line_parser.parse(static_cast<int>(passthrough.size()),
                          passthrough.data());
    const auto comm_group_configuration =
        cmd_line_parser.get<std::string>("comm-group-configuration");
    const auto logging_configuration =
        cmd_line_parser.get<std::string>("logging-configuration");
    const auto logging_folder =
        cmd_line_parser.get<std::string>("logging-folder");
    const auto num_queues_per_dim =
        cmd_line_parser.get<int>("num-queues-per-dim");
    const auto comm_scale = cmd_line_parser.get<double>("comm-scale");
    const auto injection_scale =
        cmd_line_parser.get<double>("injection-scale");
    const auto rendezvous_protocol =
        cmd_line_parser.get<bool>("rendezvous-protocol");
    const auto metrics_configuration =
        cmd_line_parser.get<std::string>("metrics-configuration");
    const auto metrics_detail =
        cmd_line_parser.get<std::string>("metrics-detail");

    AstraSim::LoggerFactory::init(logging_configuration, logging_folder);
    MetricCollector::instance().initialize(metrics_configuration,
                                           metrics_detail);
    ExecutionDriven::CompletionObserver::instance().set_hook(
        collecting_hook, nullptr);

    const auto event_queue = std::make_shared<EventQueue>();
    const auto network_parser =
        NetworkParser(fixture_root + network_dir + "network.yml");
    const auto topology = construct_topology(network_parser);
    const auto npus_count = topology->get_npus_count();
    const auto npus_count_per_dim = topology->get_npus_count_per_dim();
    const auto dims_count = topology->get_dims_count();

    CongestionAwareNetworkApi::set_event_queue(event_queue);
    CongestionAwareNetworkApi::set_topology(topology);
    const auto fluid_scheduler = std::make_shared<FluidScheduler>(
        event_queue, topology->get_directed_links(),
        network_parser.get_fluid_max_active_flows(),
        network_parser.get_fluid_max_route_memberships(),
        network_parser.get_progress_report_event_interval());
    CongestionAwareNetworkApi::set_fluid_scheduler(fluid_scheduler);

    auto network_apis =
        std::vector<std::unique_ptr<CongestionAwareNetworkApi>>();
    // The fixture's static graph carries no MEM nodes; the backend instance
    // exists only to satisfy the restored Sys constructor signature.
    const auto memory_api =
        std::make_unique<AnalyticalRemoteMemory>(fixture_root +
                                                 "/remote_memory.json");
    auto systems = std::vector<Sys*>();

    auto queues_per_dim = std::vector<int>();
    for (auto i = 0; i < dims_count; i++) {
        queues_per_dim.push_back(num_queues_per_dim);
    }

    for (int i = 0; i < npus_count; i++) {
        auto network_api = std::make_unique<CongestionAwareNetworkApi>(i);
        auto* const system =
            new Sys(i, fixture_root + "/fixture", comm_group_configuration,
                    system_path, memory_api.get(), network_api.get(),
                    npus_count_per_dim, queues_per_dim, injection_scale,
                    comm_scale, rendezvous_protocol);
        network_apis.push_back(std::move(network_api));
        systems.push_back(system);
    }

    for (int i = 0; i < npus_count; i++) {
        systems[i]->workload->fire();
    }

    fluid_scheduler->flush_pending_starts();
    fluid_scheduler->mark_event_loop_started();

    while (!event_queue->finished()) {
        event_queue->proceed();
    }

    MetricCollector::instance().finalize(systems, Sys::boostedTick());

    std::printf("[local_hbm_test] scenario=%s npus=%d sim_end=%llu\n",
                scenario.c_str(), static_cast<int>(npus_count),
                static_cast<unsigned long long>(Sys::boostedTick()));

    bool ok = true;

    // ---- Node completion ticks (numeric assertions; exact values, exact
    // single fire).  The fast scenario completes every joined comm node at
    // its HBM tick (network-first join); the slow scenario at its network
    // tick (HBM-first join).  Rank 0's COMP and rank 1's first jobs are
    // HBM-only and identical in both scenarios.
    if (scenario == "fast") {
        ok = expect_tick(0, 1, 115) && ok;  // COMP: 3 users @ 2 B/ns
        ok = expect_tick(0, 2, 125) && ok;  // SEND 60: join(net@21, hbm@125)
        ok = expect_tick(0, 3, 135) && ok;  // RECV 120: join(net@22,hbm@135)
        ok = expect_tick(0, 4, 146) && ok;  // uncharged SEND 40, net only
        ok = expect_tick(1, 1, 130) && ok;  // SEND 120: join(net@22,hbm@130)
        ok = expect_tick(1, 2, 120) && ok;  // RECV 60: join(net@21,hbm@120)
        ok = expect_tick(1, 3, 146) && ok;  // uncharged RECV 40, net only
    } else if (scenario == "slow") {
        ok = expect_tick(0, 1, 115) && ok;
        ok = expect_tick(0, 2, 132) && ok;  // join(net@132, hbm@125)
        ok = expect_tick(0, 3, 244) && ok;  // join(net@244, hbm@135)
        ok = expect_tick(0, 4, 227) && ok;
        ok = expect_tick(1, 1, 244) && ok;  // join(net@244, hbm@130)
        ok = expect_tick(1, 2, 132) && ok;  // join(net@132, hbm@120)
        ok = expect_tick(1, 3, 227) && ok;
    } else {
        // Legacy fallback (flag off, fast network): closed-form COMP
        // duration max(num_ops/peak_perf, latency + tensor/bw) = 105 ns and
        // network-only comm completion (no join, no HBM jobs).
        ok = expect_tick(0, 1, 105) && ok;
        ok = expect_tick(0, 2, 21) && ok;
        ok = expect_tick(0, 3, 22) && ok;
        ok = expect_tick(0, 4, 42) && ok;  // issues at 21: 21+1+20
        ok = expect_tick(1, 1, 22) && ok;
        ok = expect_tick(1, 2, 21) && ok;
        ok = expect_tick(1, 3, 42) && ok;
    }

    // ---- Exactly the expected set of nodes completed.
    size_t total_fires = 0;
    for (const auto& [rank, nodes] : g_completions) {
        total_fires += nodes.size();
        for (const auto& [node_id, record] : nodes) {
            (void)node_id;
            if (record.fires != 1) {
                std::fprintf(stderr,
                             "[local_hbm_test] FAIL: rank %d node %llu "
                             "fired %llu times\n",
                             rank, static_cast<unsigned long long>(node_id),
                             static_cast<unsigned long long>(record.fires));
                ok = false;
            }
        }
    }
    if (total_fires != 7) {
        std::fprintf(stderr,
                     "[local_hbm_test] FAIL: %zu terminal records, expected "
                     "7 (4 rank-0 nodes + 3 rank-1 nodes)\n",
                     total_fires);
        ok = false;
    }

    // ---- Model side-band counters (independent of the network scenario).
    const LocalHbmBandwidthModel* model0 =
        systems[0]->workload->local_hbm_bandwidth_model.get();
    const LocalHbmBandwidthModel* model1 =
        systems[1]->workload->local_hbm_bandwidth_model.get();
    if (scenario == "legacy") {
        if (model0 != nullptr || model1 != nullptr) {
            std::fprintf(stderr,
                         "[local_hbm_test] FAIL: legacy scenario must not "
                         "construct a LocalHbmBandwidthModel\n");
            ok = false;
        }
    } else if (model0 == nullptr || model1 == nullptr) {
        std::fprintf(stderr,
                     "[local_hbm_test] FAIL: LocalHbmBandwidthModel missing "
                     "(hbm-bandwidth-contention not enabled?)\n");
        ok = false;
    } else {
        ok = expect_double(model0->hbm_busy_ns(), 35.0,
                           "rank0 hbm_busy_ns") && ok;
        ok = expect_double(model0->compute_bytes_served(), 30.0,
                           "rank0 compute_bytes_served") && ok;
        ok = expect_double(model0->comm_read_bytes_served(), 60.0,
                           "rank0 comm_read_bytes_served") && ok;
        ok = expect_double(model0->comm_write_bytes_served(), 120.0,
                           "rank0 comm_write_bytes_served") && ok;
        ok = expect_uint(model0->peak_concurrent_jobs(), 3,
                         "rank0 peak_concurrent_jobs") && ok;
        ok = expect_uint(model0->redistribution_events(), 4,
                         "rank0 redistribution_events") && ok;

        ok = expect_double(model1->hbm_busy_ns(), 30.0,
                           "rank1 hbm_busy_ns") && ok;
        ok = expect_double(model1->compute_bytes_served(), 0.0,
                           "rank1 compute_bytes_served") && ok;
        ok = expect_double(model1->comm_read_bytes_served(), 120.0,
                           "rank1 comm_read_bytes_served") && ok;
        ok = expect_double(model1->comm_write_bytes_served(), 60.0,
                           "rank1 comm_write_bytes_served") && ok;
        ok = expect_uint(model1->peak_concurrent_jobs(), 2,
                         "rank1 peak_concurrent_jobs") && ok;
        ok = expect_uint(model1->redistribution_events(), 2,
                         "rank1 redistribution_events") && ok;
    }

    for (auto it : systems) {
        delete it;
    }
    systems.clear();

    AstraSim::LoggerFactory::shutdown();

    if (!ok) {
        std::fprintf(stderr, "[local_hbm_test] FAIL: see messages above\n");
        return 1;
    }
    std::printf(
        "[local_hbm_test] ALL PASS (%s): equal-split rates "
        "(1/3 -> 1/2 -> full), join orders, exact single-fire completions, "
        "and side-band counters verified\n",
        scenario.c_str());
    return 0;
}
