/******************************************************************************
This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*******************************************************************************/

#include "common/ChunkIdGenerator.hh"
#include <cassert>
#include <cstdio>
#include <cstdlib>

using namespace AstraSimAnalytical;

namespace {

[[noreturn]] void fail_chunk_lifecycle(const char* reason,
                                       const int tag,
                                       const int src,
                                       const int dest,
                                       const ChunkSize chunk_size,
                                       const int chunk_id) noexcept {
    std::fprintf(stderr,
                 "[Error] (network/analytical) ChunkIdGenerator completion "
                 "invariant failed: %s (tag=%d src=%d dest=%d size=%llu "
                 "chunk=%d)\n",
                 reason, tag, src, dest,
                 static_cast<unsigned long long>(chunk_size), chunk_id);
    std::abort();
}

}  // namespace

ChunkIdGenerator::ChunkIdGenerator() noexcept {
    chunk_id_map = {};
}

int ChunkIdGenerator::create_send_chunk_id(
    const int tag,
    const int src,
    const int dest,
    const ChunkSize chunk_size) noexcept {
    assert(tag >= 0);
    assert(src >= 0);
    assert(dest >= 0);
    assert(chunk_size > 0);

    // create key
    const auto key = std::make_tuple(tag, src, dest, chunk_size);

    // search whether the key exists
    auto entry = chunk_id_map.find(key);

    // if key doesn't exist, create new entry
    if (entry == chunk_id_map.end()) {
        entry = chunk_id_map.emplace(key, ChunkIdGeneratorEntry()).first;
    }

    // increment id and return
    entry->second.increment_send_id();
    entry->second.increment_outstanding();
    return entry->second.get_send_id();
}

int ChunkIdGenerator::create_recv_chunk_id(
    const int tag,
    const int src,
    const int dest,
    const ChunkSize chunk_size) noexcept {
    assert(tag >= 0);
    assert(src >= 0);
    assert(dest >= 0);
    assert(chunk_size > 0);

    // create key
    const auto key = std::make_tuple(tag, src, dest, chunk_size);

    // search whether the key exists
    auto entry = chunk_id_map.find(key);

    // key doesn't exist, create new entry
    if (entry == chunk_id_map.end()) {
        entry = chunk_id_map.emplace(key, ChunkIdGeneratorEntry()).first;
    }

    // increment recv id and return
    entry->second.increment_recv_id();
    return entry->second.get_recv_id();
}

void ChunkIdGenerator::complete(const int tag,
                                const int src,
                                const int dest,
                                const ChunkSize chunk_size,
                                const int chunk_id) noexcept {
    const auto key = std::make_tuple(tag, src, dest, chunk_size);
    const auto entry = chunk_id_map.find(key);
    if (entry == chunk_id_map.end()) {
        fail_chunk_lifecycle("unknown key", tag, src, dest, chunk_size,
                             chunk_id);
    }

    auto& state = entry->second;
    if (chunk_id < 0 || state.outstanding() == 0) {
        fail_chunk_lifecycle("duplicate completion or no outstanding send", tag,
                             src, dest, chunk_size, chunk_id);
    }
    if (state.get_send_id() < chunk_id) {
        fail_chunk_lifecycle("chunk id was not generated by sim_send", tag,
                             src, dest, chunk_size, chunk_id);
    }

    state.decrement_outstanding();
    if (state.outstanding() == 0 &&
        state.get_send_id() == state.get_recv_id()) {
        chunk_id_map.erase(entry);
    }
}

size_t ChunkIdGenerator::size() const noexcept {
    return chunk_id_map.size();
}
