/******************************************************************************
This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.

completion_observer_fixture_main.cc -- phase-1 step 1-3 hook-count fixture.

Runs the static ET simulation (entry replicated from
congestion_aware/main.cc -- test-only duplicate, never part of the baseline
gates) with a counting CompletionObserver hook installed, over a synthetic
3-node-per-rank graph generated by tests/make_completion_fixture_et.py:

  node 0 INVALID_NODE   -> Workload::skip_invalid   (Skipped,   site 1)
  node 1 COMP_NODE      -> generic wlhd branch      (Success,   site 2)
  node 2 COMM_COLL_NODE -> collective branch        (Success,   site 3)

Assertions (per step-1-3 acceptance): every supported terminal status is
constructible and exercised, each of the three insertion sites fires, and
the hook count equals the number of completed nodes (54 ranks x 3 = 162).

Build: the CMake target AstraSim_Analytical_Congestion_Aware_CompletionFixture
(build with cmake --build build/astra_analytical/build_congestion_aware -j).
Run (from template/astra-sim-sh_3.0, after generating the synthetic trace):
  python3 astra-sim/workload/execution_driven/tests/make_completion_fixture_et.py
  build/astra_analytical/build_congestion_aware/bin/\
      AstraSim_Analytical_Congestion_Aware_CompletionFixture \
      --workload-configuration=sh_test_mesh/generated/completion_fixture/fixture \
      --comm-group-configuration=sh_test_mesh/generated/runtime_config/\
face_case5_config_c__validation-160gib__edge_remote_memory_pool/comm_group.json \
      --system-configuration=sh_test_mesh/generated/runtime_config/\
face_case5_config_c__validation-160gib__edge_remote_memory_pool/system.json \
      --remote-memory-configuration=sh_test_mesh/generated/runtime_config/\
face_case5_config_c__validation-160gib__edge_remote_memory_pool/remote_memory.json \
      --network-configuration=sh_test_mesh/generated/runtime_config/\
face_case5_config_c__validation-160gib__edge_remote_memory_pool/network.yml \
      --logging-folder=off
*******************************************************************************/

#include "astra-sim/common/Logging.hh"
#include "astra-sim/workload/MetricCollector.hh"
#include "astra-sim/workload/execution_driven/CompletionObserver.hh"
#include "common/CmdLineParser.hh"
#include "congestion_aware/CongestionAwareNetworkApi.hh"
#include <astra-network-analytical/common/EventQueue.h>
#include <astra-network-analytical/common/NetworkParser.h>
#include <astra-network-analytical/congestion_aware/Helper.h>
#include <remote_memory_backend/analytical/AnalyticalRemoteMemory.hh>

#include <cstdio>
#include <cstdlib>

using namespace AstraSim;
using namespace Analytical;
using namespace AstraSimAnalytical;
using namespace AstraSimAnalyticalCongestionAware;
using namespace NetworkAnalytical;
using namespace NetworkAnalyticalCongestionAware;

namespace {

struct FixtureCounters {
    uint64_t total = 0;
    uint64_t success = 0;
    uint64_t skipped = 0;
    uint64_t site_skip = 0;     // node id % 3 == 0 (skip_invalid)
    uint64_t site_generic = 0;  // node id % 3 == 1 (generic wlhd branch)
    uint64_t site_coll = 0;     // node id % 3 == 2 (collective branch)
    uint64_t site_remote_mem = 0;  // node id 3 (remote FIFO -> wlhd branch)
    uint64_t site_hbm_restore = 0;  // node id 4 (HBM model -> wlhd branch)
};

void counting_hook(void* ctx, int /*rank*/, uint64_t node_id,
                   const char* /*request_id*/, const char* /*stage*/,
                   uint64_t /*generation*/, uint64_t /*tick*/,
                   int terminal_status) {
    auto* const counters = static_cast<FixtureCounters*>(ctx);
    counters->total++;
    switch (node_id % 5) {
        case 0:
            counters->site_skip++;
            break;
        case 2:
            counters->site_coll++;
            break;
        case 3:
            counters->site_remote_mem++;
            break;
        case 4:
            counters->site_hbm_restore++;
            break;
        default:
            counters->site_generic++;
            break;
    }
    if (terminal_status ==
        static_cast<int>(ExecutionDriven::NodeTerminalStatus::Success)) {
        counters->success++;
    } else if (terminal_status ==
               static_cast<int>(ExecutionDriven::NodeTerminalStatus::Skipped)) {
        counters->skipped++;
    } else {
        std::fprintf(stderr, "[fixture] unexpected terminal_status=%d\n",
                     terminal_status);
        std::exit(1);
    }
}

}  // namespace

int main(int argc, char* argv[]) {
    // Parse command line arguments
    auto cmd_line_parser = CmdLineParser(argv[0]);
    cmd_line_parser.parse(argc, argv);

    // Get command line arguments
    const auto workload_configuration =
        cmd_line_parser.get<std::string>("workload-configuration");
    const auto comm_group_configuration =
        cmd_line_parser.get<std::string>("comm-group-configuration");
    const auto system_configuration =
        cmd_line_parser.get<std::string>("system-configuration");
    const auto remote_memory_configuration =
        cmd_line_parser.get<std::string>("remote-memory-configuration");
    const auto network_configuration =
        cmd_line_parser.get<std::string>("network-configuration");
    const auto logging_configuration =
        cmd_line_parser.get<std::string>("logging-configuration");
    const auto logging_folder =
        cmd_line_parser.get<std::string>("logging-folder");
    const auto num_queues_per_dim =
        cmd_line_parser.get<int>("num-queues-per-dim");
    const auto comm_scale = cmd_line_parser.get<double>("comm-scale");
    const auto injection_scale = cmd_line_parser.get<double>("injection-scale");
    const auto rendezvous_protocol =
        cmd_line_parser.get<bool>("rendezvous-protocol");
    const auto metrics_configuration =
        cmd_line_parser.get<std::string>("metrics-configuration");
    const auto metrics_detail =
        cmd_line_parser.get<std::string>("metrics-detail");

    AstraSim::LoggerFactory::init(logging_configuration, logging_folder);

    // Step-1-3 fixture: install the counting hook BEFORE the simulation runs.
    static FixtureCounters counters;
    ExecutionDriven::CompletionObserver::instance().set_hook(counting_hook,
                                                             &counters);

    // Initialize side-band metrics collection early; with the default
    // "off" detail level this performs no work at all (doc sec.5.6/5.8).
    MetricCollector::instance().initialize(metrics_configuration,
                                           metrics_detail);

    // Instantiate event queue
    const auto event_queue = std::make_shared<EventQueue>();

    // Generate topology
    const auto network_parser = NetworkParser(network_configuration);
    const auto topology = construct_topology(network_parser);

    // Get topology information
    const auto npus_count = topology->get_npus_count();
    const auto npus_count_per_dim = topology->get_npus_count_per_dim();
    const auto dims_count = topology->get_dims_count();

    // Set up Network API
    CongestionAwareNetworkApi::set_event_queue(event_queue);
    CongestionAwareNetworkApi::set_topology(topology);
    const auto fluid_scheduler = std::make_shared<FluidScheduler>(
        event_queue, topology->get_directed_links(),
        network_parser.get_fluid_max_active_flows(),
        network_parser.get_fluid_max_route_memberships(),
        network_parser.get_progress_report_event_interval());
    CongestionAwareNetworkApi::set_fluid_scheduler(fluid_scheduler);

    // Create ASTRA-sim related resources
    auto network_apis =
        std::vector<std::unique_ptr<CongestionAwareNetworkApi>>();
    const auto memory_api =
        std::make_unique<AnalyticalRemoteMemory>(remote_memory_configuration);
    auto systems = std::vector<Sys*>();

    auto queues_per_dim = std::vector<int>();
    for (auto i = 0; i < dims_count; i++) {
        queues_per_dim.push_back(num_queues_per_dim);
    }

    for (int i = 0; i < npus_count; i++) {
        // create network and system
        auto network_api = std::make_unique<CongestionAwareNetworkApi>(i);
        auto* const system =
            new Sys(i, workload_configuration, comm_group_configuration,
                    system_configuration, memory_api.get(), network_api.get(),
                    npus_count_per_dim, queues_per_dim, injection_scale,
                    comm_scale, rendezvous_protocol);

        // push back network and system
        network_apis.push_back(std::move(network_api));
        systems.push_back(system);
    }

    // Initiate ASTRA-sim simulation
    for (int i = 0; i < npus_count; i++) {
        systems[i]->workload->fire();
    }

    fluid_scheduler->flush_pending_starts();
    fluid_scheduler->mark_event_loop_started();

    // run simulation
    while (!event_queue->finished()) {
        event_queue->proceed();
    }

    // Emit all metric records after the event loop, while Statistics are
    // still alive; no-op when metrics are disabled (doc sec.5.6).
    MetricCollector::instance().finalize(systems, Sys::boostedTick());

    // Step-1-3 acceptance assertions:
    //  - the hook count equals the number of completed nodes
    //    (54 ranks x 3 nodes = 162);
    //  - all three terminal insertion sites fired (54 each);
    //  - both supported statuses occurred and match their sites
    //    (site 1 = Skipped, sites 2/3 = Success).
    // 26 boundary-port ranks (9x6 mesh outer ring) also emit the remote
    // MEM node; the other 28 ranks emit 4 nodes each.
    const uint64_t expected_remote_site = 26;
    const uint64_t expected_nodes = npus_count * 4 + expected_remote_site;
    std::printf("[fixture] rank_total=%u nodes_per_rank=5 expected_total=%llu\n",
                static_cast<unsigned>(npus_count),
                static_cast<unsigned long long>(expected_nodes));
    std::printf("[fixture] hook_total=%llu success=%llu skipped=%llu "
                "site_skip=%llu site_generic=%llu site_coll=%llu "
                "site_remote_mem=%llu site_hbm_restore=%llu\n",
                static_cast<unsigned long long>(counters.total),
                static_cast<unsigned long long>(counters.success),
                static_cast<unsigned long long>(counters.skipped),
                static_cast<unsigned long long>(counters.site_skip),
                static_cast<unsigned long long>(counters.site_generic),
                static_cast<unsigned long long>(counters.site_coll),
                static_cast<unsigned long long>(counters.site_remote_mem),
                static_cast<unsigned long long>(counters.site_hbm_restore));

    bool ok = true;
    if (counters.total != expected_nodes) {
        std::fprintf(stderr,
                     "[fixture] FAIL: hook count %llu != completed nodes %llu\n",
                     static_cast<unsigned long long>(counters.total),
                     static_cast<unsigned long long>(expected_nodes));
        ok = false;
    }
    if (counters.site_skip != npus_count ||
        counters.site_generic != npus_count ||
        counters.site_coll != npus_count ||
        counters.site_remote_mem != expected_remote_site ||
        counters.site_hbm_restore != npus_count) {
        std::fprintf(stderr,
                     "[fixture] FAIL: each terminal site must fire once per "
                     "rank (54/54/54/26/54), got %llu/%llu/%llu/%llu/%llu\n",
                     static_cast<unsigned long long>(counters.site_skip),
                     static_cast<unsigned long long>(counters.site_generic),
                     static_cast<unsigned long long>(counters.site_coll),
                static_cast<unsigned long long>(counters.site_remote_mem),
                static_cast<unsigned long long>(counters.site_hbm_restore));
        ok = false;
    }
    if (counters.skipped != npus_count || counters.success != expected_nodes - npus_count) {
        std::fprintf(stderr,
                     "[fixture] FAIL: expected skipped=%llu success=%llu, "
                     "got %llu/%llu\n",
                     static_cast<unsigned long long>(npus_count),
                     static_cast<unsigned long long>(expected_nodes - npus_count),
                     static_cast<unsigned long long>(counters.skipped),
                     static_cast<unsigned long long>(counters.success));
        ok = false;
    }

    for (auto it : systems) {
        delete it;
    }
    systems.clear();

    // terminate simulation
    AstraSim::LoggerFactory::shutdown();

    if (!ok) {
        std::fprintf(stderr, "[fixture] FAIL: see messages above\n");
        return 1;
    }
    std::printf("[fixture] ALL PASS: hook count == completed nodes, all "
                "three terminal sites fired, both statuses verified\n");
    return 0;
}
