/******************************************************************************
This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*******************************************************************************/

/**

hbm_nway_test.cc -- N-way HBM contention fixture (hbm-bandwidth-contention).

Runs the static ET simulation (entry replicated from
congestion_aware/main.cc -- test-only duplicate, never part of the baseline
gates) over the synthetic 2-rank graph generated by
tests/make_hbm_nway_fixture.py, with a CompletionObserver hook capturing
every node's terminal tick. The fixture exercises the N-way equal-split
LocalHbmBandwidthModel end to end:

  rank 0: COMP(300B) + KV-restore(600B) + charged COMM_SEND(900B) -- the
          three-way equal-split scenario -- plus an uncharged
          (hbm-charge=false) 64B send that must NOT create an HBM job, and
          a calibrated COMP (duration_micros=5, 中-5 honor pin) that must
          bypass the model entirely;
  rank 1: COMP(300B) + KV-restore(600B) + charged COMM_RECV(900B) +
          MEM_STORE(1200B, hbm-access-mode=1 pool endpoint) -- the four-way
          split with both join flavors (network-side and port-side).

Assertions (local-mem-bw = 3000 GB/s = 3 B/ns, local-mem-latency = 100 ns;
all completions land on integer ticks, so equalities are exact):

  contention ON:
    - 3-way 1/3-rate numeric: rank0 COMP terminal == 400
      (100 latency + 300B / (3/3 B/ns)), RESTORE == 600 (2-way 1.5 B/ns
      tail), charged send == 700 (solo 3 B/ns tail; join with the faster
      network side);
    - 4-way on rank 1: COMP == 500, RESTORE == 800, RECV == 1000,
      MEM_STORE == 1100 (join of port@300 and HBM@1100 -> 1100);
    - 1/3-rate evidence: COMP(300B) completes exactly 300 ns after the
      latency under three concurrent streamers (full-rate would be 100 ns);
    - redistribution: after COMP completes at 400 the RESTORE rate doubles
      (300 remaining bytes served in 200 ns at 1.5 B/ns -> terminal 600);
    - hbm-charge=false: comm_read bytes == 900 exactly (the 64B pass-through
      send contributes nothing); its terminal is strictly after its issue
      (>= 800, network-only);
    - 中-5 honor pin: rank0 #4 calibrated COMP terminal == 5400（honor：不进
      流体模型；单 COMP 槽使其在 node0 后发射，终点=发射+5000）;
    - join fires exactly once: every (rank, node) terminal is recorded
      exactly once; total terminals == 9;
    - served bytes by category match the issued bytes;
    - peak concurrent jobs: 3 (rank0) / 4 (rank1); redistribution events:
      4 (rank0) / 6 (rank1).
  contention OFF (legacy A/B):
    - only COMP + restore share (50/50): COMP == 300, RESTORE == 400;
    - comm_read/comm_write/pool_read/pool_write served bytes == 0;
    - peak concurrent jobs == 2;
    - 中-5 honor pin: rank0 #4 calibrated COMP terminal == 5300（honor：不进
      流体模型；单 COMP 槽使其在 node0 后发射，终点=发射+5000）.

Build: the CMake target AstraSim_Analytical_Congestion_Aware_HbmNwayTest
(build with cmake --build build/astra_analytical/build_congestion_aware -j).
Run (from template/astra-sim-sh_3.0, after generating the fixture):
  python3 astra-sim/workload/execution_driven/tests/make_hbm_nway_fixture.py
  build/astra_analytical/build_congestion_aware/bin/\
AstraSim_Analytical_Congestion_Aware_HbmNwayTest \
    --workload-configuration=sh_test_mesh/generated/hbm_nway_fixture/fixture \
    --comm-group-configuration=sh_test_mesh/generated/hbm_nway_fixture/comm_group.json \
    --system-configuration=sh_test_mesh/generated/hbm_nway_fixture/system_on.json \
    --remote-memory-configuration=sh_test_mesh/generated/hbm_nway_fixture/remote_memory.json \
    --network-configuration=sh_test_mesh/generated/hbm_nway_fixture/network.yml \
    --logging-folder=off
  (then the same with system_off.json for the legacy A/B assertions)
Exit code 0 on ALL PASS.
*******************************************************************************/

#include "astra-sim/common/Logging.hh"
#include "astra-sim/workload/LocalHbmBandwidthModel.hh"
#include "astra-sim/workload/MetricCollector.hh"
#include "astra-sim/workload/Workload.hh"
#include "astra-sim/workload/execution_driven/CompletionObserver.hh"
#include "common/CmdLineParser.hh"
#include "congestion_aware/CongestionAwareNetworkApi.hh"
#include <astra-network-analytical/common/EventQueue.h>
#include <astra-network-analytical/common/NetworkParser.h>
#include <astra-network-analytical/congestion_aware/Helper.h>
#include <remote_memory_backend/analytical/AnalyticalRemoteMemory.hh>

#include <cstdio>
#include <cstdlib>
#include <map>
#include <utility>

using namespace AstraSim;
using namespace Analytical;
using namespace AstraSimAnalytical;
using namespace AstraSimAnalyticalCongestionAware;
using namespace NetworkAnalytical;
using namespace NetworkAnalyticalCongestionAware;

namespace {

struct FixtureState {
    // (rank, node_id) -> terminal tick; duplicates would overwrite, so a
    // per-key counter proves the join fired exactly once.
    std::map<std::pair<int, uint64_t>, uint64_t> terminal_tick;
    std::map<std::pair<int, uint64_t>, uint64_t> terminal_count;
};

void recording_hook(void* ctx, int rank, uint64_t node_id,
                    const char* /*request_id*/, const char* /*stage*/,
                    uint64_t /*generation*/, uint64_t tick,
                    int terminal_status) {
    auto* const state = static_cast<FixtureState*>(ctx);
    if (terminal_status !=
        static_cast<int>(ExecutionDriven::NodeTerminalStatus::Success)) {
        std::fprintf(stderr,
                     "[hbm_nway_test] FAIL: unexpected terminal status %d "
                     "for rank %d node %llu\n",
                     terminal_status, rank,
                     static_cast<unsigned long long>(node_id));
        std::exit(1);
    }
    const auto key = std::make_pair(rank, node_id);
    state->terminal_tick[key] = tick;
    ++state->terminal_count[key];
}

uint64_t tick_of(const FixtureState& state, int rank, uint64_t node_id) {
    const auto it = state.terminal_tick.find({rank, node_id});
    if (it == state.terminal_tick.end()) {
        std::fprintf(stderr,
                     "[hbm_nway_test] FAIL: rank %d node %llu never "
                     "terminated\n",
                     rank, static_cast<unsigned long long>(node_id));
        std::exit(1);
    }
    return it->second;
}

void expect_eq_u64(uint64_t got, uint64_t want, const char* what) {
    if (got != want) {
        std::fprintf(stderr,
                     "[hbm_nway_test] FAIL: %s = %llu, expected %llu\n",
                     what, static_cast<unsigned long long>(got),
                     static_cast<unsigned long long>(want));
        std::exit(1);
    }
}

void expect_eq_d(double got, double want, const char* what) {
    // The fluid model accumulates per-step doubles; integer-valued fixture
    // bytes/ticks must reproduce exactly (tolerance only absorbs IEEE
    // summation noise below the printed precision).
    if (got < want - 1e-6 || got > want + 1e-6) {
        std::fprintf(stderr,
                     "[hbm_nway_test] FAIL: %s = %.9f, expected %.9f\n",
                     what, got, want);
        std::exit(1);
    }
}

}  // namespace

int main(int argc, char* argv[]) {
    auto cmd_line_parser = CmdLineParser(argv[0]);
    cmd_line_parser.parse(argc, argv);

    const auto workload_configuration =
        cmd_line_parser.get<std::string>("workload-configuration");
    const auto comm_group_configuration =
        cmd_line_parser.get<std::string>("comm-group-configuration");
    const auto system_configuration =
        cmd_line_parser.get<std::string>("system-configuration");
    const auto remote_memory_configuration =
        cmd_line_parser.get<std::string>("remote-memory-configuration");
    const auto network_configuration =
        cmd_line_parser.get<std::string>("network-configuration");
    const auto logging_folder =
        cmd_line_parser.get<std::string>("logging-folder");
    const auto num_queues_per_dim =
        cmd_line_parser.get<int>("num-queues-per-dim");
    const auto comm_scale = cmd_line_parser.get<double>("comm-scale");
    const auto injection_scale =
        cmd_line_parser.get<double>("injection-scale");
    const auto rendezvous_protocol =
        cmd_line_parser.get<bool>("rendezvous-protocol");

    AstraSim::LoggerFactory::init("empty", logging_folder);

    static FixtureState fixture;
    ExecutionDriven::CompletionObserver::instance().set_hook(recording_hook,
                                                             &fixture);

    MetricCollector::instance().initialize("empty", "off");

    const auto event_queue = std::make_shared<EventQueue>();
    const auto network_parser = NetworkParser(network_configuration);
    const auto topology = construct_topology(network_parser);
    const auto npus_count = topology->get_npus_count();
    const auto npus_count_per_dim = topology->get_npus_count_per_dim();
    const auto dims_count = topology->get_dims_count();

    CongestionAwareNetworkApi::set_event_queue(event_queue);
    CongestionAwareNetworkApi::set_topology(topology);
    const auto fluid_scheduler = std::make_shared<FluidScheduler>(
        event_queue, topology->get_directed_links(),
        network_parser.get_fluid_max_active_flows(),
        network_parser.get_fluid_max_route_memberships(),
        network_parser.get_progress_report_event_interval());
    CongestionAwareNetworkApi::set_fluid_scheduler(fluid_scheduler);

    auto network_apis =
        std::vector<std::unique_ptr<CongestionAwareNetworkApi>>();
    const auto memory_api =
        std::make_unique<AnalyticalRemoteMemory>(remote_memory_configuration);
    auto systems = std::vector<Sys*>();

    auto queues_per_dim = std::vector<int>();
    for (auto i = 0; i < dims_count; i++) {
        queues_per_dim.push_back(num_queues_per_dim);
    }

    for (int i = 0; i < npus_count; i++) {
        auto network_api = std::make_unique<CongestionAwareNetworkApi>(i);
        auto* const system =
            new Sys(i, workload_configuration, comm_group_configuration,
                    system_configuration, memory_api.get(), network_api.get(),
                    npus_count_per_dim, queues_per_dim, injection_scale,
                    comm_scale, rendezvous_protocol);
        network_apis.push_back(std::move(network_api));
        systems.push_back(system);
    }

    for (int i = 0; i < npus_count; i++) {
        systems[i]->workload->fire();
    }
    fluid_scheduler->flush_pending_starts();
    fluid_scheduler->mark_event_loop_started();
    while (!event_queue->finished()) {
        event_queue->proceed();
    }

    const bool contention_on = systems[0]->hbm_bandwidth_contention;
    const LocalHbmBandwidthModel* model0 =
        systems[0]->workload->local_hbm_bandwidth_model.get();
    const LocalHbmBandwidthModel* model1 =
        systems[1]->workload->local_hbm_bandwidth_model.get();
    if (model0 == nullptr || model1 == nullptr) {
        std::fprintf(stderr,
                     "[hbm_nway_test] FAIL: LocalHbmBandwidthModel missing "
                     "(both system variants must construct it)\n");
        return 1;
    }

    // Join fired exactly once per node: 5 nodes (rank0) + 4 nodes (rank1) = 9.
    expect_eq_u64(fixture.terminal_count.size(), 9,
                  "distinct terminated (rank,node) pairs");
    for (const auto& [key, count] : fixture.terminal_count) {
        expect_eq_u64(count, 1, "join/terminal fired exactly once");
    }

    std::printf("[hbm_nway_test] mode=%s terminals:",
                contention_on ? "contention-ON" : "contention-OFF");
    for (int rank = 0; rank < 2; ++rank) {
        for (uint64_t id = 0; id < (rank == 0 ? 5 : 4); ++id) {
            std::printf(" r%d#%llu=%llu", rank,
                        static_cast<unsigned long long>(id),
                        static_cast<unsigned long long>(
                            tick_of(fixture, rank, id)));
        }
    }
    std::printf("\n");

    if (contention_on) {
        // ---- rank 0: three-way equal split (COMP + restore + comm read) --
        // 1/3-rate numeric assertion: COMP(300B) completes 300 ns AFTER the
        // 100 ns latency (full rate would finish at 200).
        expect_eq_u64(tick_of(fixture, 0, 0), 400, "rank0 COMP terminal");
        // Redistribution: COMP done at 400 -> 2-way split at 1.5 B/ns; the
        // restore's remaining 300 B take 200 ns.
        expect_eq_u64(tick_of(fixture, 0, 1), 600, "rank0 restore terminal");
        // Solo tail at 3 B/ns: the comm job's remaining 300 B take 100 ns.
        expect_eq_u64(tick_of(fixture, 0, 2), 700,
                      "rank0 charged send terminal (join)");
        // The uncharged pass-through send issues only after the comm slot
        // frees at 700 and carries no HBM job.
        if (tick_of(fixture, 0, 3) < 700) {
            std::fprintf(stderr,
                         "[hbm_nway_test] FAIL: uncharged send terminal %llu "
                         "< issue time 700\n",
                         static_cast<unsigned long long>(
                             tick_of(fixture, 0, 3)));
            return 1;
        }
        expect_eq_d(model0->compute_bytes_served(), 300.0,
                    "rank0 compute bytes served");
        expect_eq_d(model0->restore_bytes_served(), 600.0,
                    "rank0 restore bytes served");
        expect_eq_d(model0->comm_read_bytes_served(), 900.0,
                    "rank0 comm_read bytes served (hbm-charge=false "
                    "pass-through excluded)");
        expect_eq_d(model0->comm_write_bytes_served(), 0.0,
                    "rank0 comm_write bytes served");
        expect_eq_d(model0->pool_read_bytes_served(), 0.0,
                    "rank0 pool_read bytes served");
        expect_eq_d(model0->pool_write_bytes_served(), 0.0,
                    "rank0 pool_write bytes served");
        expect_eq_u64(model0->peak_concurrent_jobs(), 3,
                      "rank0 peak concurrent jobs");
        // 中-4④ batch-level derivation (face rule: one count per completion
        // BATCH with survivors, not per completed job):
        //   issue side: restore joins {COMP} (+1), comm read joins
        //   {COMP,restore} (+1) = 2;
        //   completion side: COMP batch at 400 (survivors restore+comm, +1),
        //   restore batch at 600 (survivor comm, +1), comm batch at 700
        //   (no survivor, 0) = 2.
        // Every completion lands in its own transition batch (distinct ticks
        // 400/600/700), so batch-level == per-job here and the total stays 4;
        // had two jobs completed in the same batch the count would be LOWER
        // than the old per-job semantics (one count per batch).
        expect_eq_u64(model0->redistribution_events(), 4,
                      "rank0 redistribution events");
        // 中-5 honor pin: the calibrated COMP (duration_micros=5) never
        // enters the fluid model. The static single COMP slot serializes
        // it after node 0 completes at 400, and the honor path registers
        // +5000 ns from its issue tick -> terminal exactly 5400. (Pre-fix
        // it entered the model at 400 and drained as a 3rd streamer,
        // moving the restore to 650 -- the timings above pin that too.)
        expect_eq_u64(tick_of(fixture, 0, 4), 5400,
                      "rank0 calibrated COMP terminal (calibration honor)");
        expect_eq_d(model0->compute_bytes_served(), 300.0,
                    "rank0 compute bytes served (calibrated node excluded)");

        // ---- rank 1: four-way split + both join flavors ------------------
        expect_eq_u64(tick_of(fixture, 1, 0), 500, "rank1 COMP terminal");
        expect_eq_u64(tick_of(fixture, 1, 1), 800, "rank1 restore terminal");
        expect_eq_u64(tick_of(fixture, 1, 2), 1000,
                      "rank1 charged recv terminal (network join)");
        // Pool endpoint join: the port transaction finishes at ~300 ns; the
        // HBM job at 1100 ns (900 B served by t=1000 under the 4/3/2-way
        // splits, the last 300 B solo at 3 B/ns); the node waits for both.
        expect_eq_u64(tick_of(fixture, 1, 3), 1100,
                      "rank1 pool MEM_STORE terminal (port join)");
        expect_eq_d(model1->compute_bytes_served(), 300.0,
                    "rank1 compute bytes served");
        expect_eq_d(model1->restore_bytes_served(), 600.0,
                    "rank1 restore bytes served");
        expect_eq_d(model1->comm_write_bytes_served(), 900.0,
                    "rank1 comm_write bytes served");
        expect_eq_d(model1->pool_read_bytes_served(), 1200.0,
                    "rank1 pool_read bytes served");
        expect_eq_d(model1->comm_read_bytes_served(), 0.0,
                    "rank1 comm_read bytes served");
        expect_eq_u64(model1->peak_concurrent_jobs(), 4,
                      "rank1 peak concurrent jobs");
        // 中-4④ batch-level derivation (face rule): issue side = restore,
        // comm write, pool read each join a non-empty set (+3); completion
        // side: COMP batch at 500 (+1), restore batch at 800 (+1), comm
        // write HBM batch at 1000 (pool survives, +1), pool batch at 1100
        // (no survivor, 0) = 3. All completion ticks are distinct
        // (500/800/1000/1100 -> one job per batch), so batch-level ==
        // per-job and the total stays 6; same-batch multi-completions would
        // count once per batch (fewer than per-job).
        expect_eq_u64(model1->redistribution_events(), 6,
                      "rank1 redistribution events");
    } else {
        // ---- legacy A/B: two-user 50/50 only ------------------------------
        expect_eq_u64(tick_of(fixture, 0, 0), 300, "rank0 COMP terminal");
        expect_eq_u64(tick_of(fixture, 0, 1), 400, "rank0 restore terminal");
        expect_eq_u64(tick_of(fixture, 1, 0), 300, "rank1 COMP terminal");
        expect_eq_u64(tick_of(fixture, 1, 1), 400, "rank1 restore terminal");
        // 中-5 honor pin (OFF config): the model still exists (restore
        // sharing) and the calibrated COMP still bypasses it -- it issues
        // when the COMP slot frees at 300 and honors +5000 ns -> terminal
        // exactly 5300 (pre-fix it drained solo 400->500 == 500).
        expect_eq_u64(tick_of(fixture, 0, 4), 5300,
                      "rank0 calibrated COMP terminal (calibration honor)");
        // MEM_STORE completes on the port transaction alone (100 ns latency
        // + 1200 B / 6 B/ns = 300 ns).
        expect_eq_u64(tick_of(fixture, 1, 3), 300,
                      "rank1 MEM_STORE port-only terminal");
        for (int rank = 0; rank < 2; ++rank) {
            const LocalHbmBandwidthModel* model =
                systems[rank]->workload->local_hbm_bandwidth_model.get();
            expect_eq_d(model->comm_read_bytes_served(), 0.0,
                        "rank comm_read bytes served");
            expect_eq_d(model->comm_write_bytes_served(), 0.0,
                        "rank comm_write bytes served");
            expect_eq_d(model->pool_read_bytes_served(), 0.0,
                        "rank pool_read bytes served");
            expect_eq_d(model->pool_write_bytes_served(), 0.0,
                        "rank pool_write bytes served");
            expect_eq_u64(model->peak_concurrent_jobs(), 2,
                          "rank peak concurrent jobs");
        }
    }

    for (auto it : systems) {
        delete it;
    }
    systems.clear();
    AstraSim::LoggerFactory::shutdown();

    std::printf("[hbm_nway_test] ALL PASS (%s)\n",
                contention_on ? "contention-ON" : "contention-OFF");
    return 0;
}
