/******************************************************************************
This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*******************************************************************************/

#pragma once

#include <cstdint>

namespace AstraSimAnalytical {

/**
 * ChunkIdGeneratorEntry tracks the chunk id generated
 * for sim_send() and sim_recv() calls
 * per each (tag, src, dest, chunk_size) tuple.
 */
class ChunkIdGeneratorEntry {
  public:
    /**
     * Constructur.
     */
    ChunkIdGeneratorEntry() noexcept;

    /**
     * Get the chunk id for sim_send() call.
     *
     * @return chunk id for sim_send() call
     */
    [[nodiscard]] int get_send_id() const noexcept;

    /**
     * Get the chunk id for sim_recv() call.
     *
     * @return chunk id for sim_recv() call
     */
    [[nodiscard]] int get_recv_id() const noexcept;

    /**
     * Increment the chunk id for sim_send() call.
     */
    void increment_send_id() noexcept;

    /**
     * Increment the chunk id for sim_recv() call.
     */
    void increment_recv_id() noexcept;

    /// Number of logical transmissions generated by sim_send() that have
    /// not yet completed their send/recv callback pair.
    [[nodiscard]] uint64_t outstanding() const noexcept;

    /// Account for a new logical transmission generated by sim_send().
    void increment_outstanding() noexcept;

    /// Account for one fully paired callback completion.
    void decrement_outstanding() noexcept;

  private:
    /// current available chunk id for sim_send() call
    int send_id;

    /// current available chunk id for sim_recv() call
    int recv_id;

    /// Logical sends that have not reached CallbackTracker::pop_entry().
    uint64_t outstanding_;
};

}  // namespace AstraSimAnalytical
